services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: wallet-db
      POSTGRES_USER: wallet-user
      POSTGRES_PASSWORD: wallet-password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet-user -d wallet-db"]
      interval: 2s
      timeout: 2s
      retries: 10
      
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./config.env
    ports:
      - "9000:9000"

  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_DB: wallet-db-test
      POSTGRES_USER: wallet-user
      POSTGRES_PASSWORD: wallet-password
    ports:
      - "5433:5432"